import { type NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Greeting from "../components/Greetings/Greeting";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col items-center justify-center gap-6 border-slate-500 dark:border-slate-300 lg:border-l">
        <Greeting />
        <Link href="/feed" className="rounded-full bg-twitter px-4 py-2">
          Go to feed
        </Link>
      </div>
    </>
  );
};

export default Home;
