import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "World" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className="text-2xl text-black dark:text-white">
        {hello.data ? hello.data.greeting : "Loading tRPC query..."}
      </p>
    </>
  );
};

export default Home;
